version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: mkdir ~/junit
      - run:
          command: node node_modules\mocha\bin\mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - run: npm install --prune          
      - persist_to_workspace:
          root: ./
          paths:
            - ./**
  push:
    docker:
      - image: octopusdeploy/octo:4.37.0-alpine
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: mkdir /tmp/out
      - run: octo pack --id $CIRCLE_PROJECT_REPONAME --version 1.0.$CIRCLE_BUILD_NUM --outFolder /tmp/out --format zip 
      - run: octo push --package /tmp/out/$CIRCLE_PROJECT_REPONAME.1.0.$CIRCLE_BUILD_NUM.zip --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY 
      - store_artifacts:
          path: /tmp/out
workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
