defaults: &defaults
  working_directory: /tmp
  docker:
    - image: buildpack-deps:jessie

version: 2
jobs:
  flow:
    <<: *defaults
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: ./
          paths:
            - ./**

  downstream:
    <<: *defaults
    docker:
      - image: octopusdeploy/octo:4.37.0-alpine
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: mkdir /tmp/out
      - run: octo pack --id $CIRCLE_PROJECT_REPONAME --version 1.0.$CIRCLE_BUILD_NUM --outFolder /tmp/out --format zip 
      - store_artifacts:
          path: /tmp/out/$CIRCLE_PROJECT_REPONAME.1.0.$CIRCLE_BUILD_NUM.zip
workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
