defaults: &defaults
  working_directory: /tmp
  docker:
    - image: buildpack-deps:jessie

version: 2
jobs:
  flow:
    <<: *defaults
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      - persist_to_workspace:
          root: ./
          paths:
            - echo-output

  downstream:
    <<: *defaults
    docker:
      - image: octopusdeploy/octo:4.37.0-alpine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls ./
      - run: ls /
      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
